# sum_stats is a csv file
# neale_var_ref is only required if using files from the Neale lab round 2 2018 analysis
input:
    sum_stats: "metabo.csv"
    label: "metabo"
    neale_var_ref: "/nfs/turbo/sph-jvmorr/gwas_summary_statistics/NealeRound2_2018/variants.tsv.bgz"

analysis:
    # LD pruning options:
    # r2_thresh: threshold for pairwise r^2 between variants
    # clump_kb Maximum distance for pruning.
    # ref_path Path to plink format reference data
    ldprune:
        r2_thresh: 0.01
        ld_seed: [0]
        clump_kb: [10000]
        ref_path: "/nfs/turbo/sph-jvmorr/ld_reference_files/1kg_plink/EUR"
    # GFA options:
    # gfa_params: If "default", will use default parameters, otherwise provide an R string with values, eg "list(max_iter = 5000)".
    # mode: Either "z-score" to use z-score or "b-std" to use standardized effect estimates.
    # nmiss_thresh: Maximum number of missing studies per snp. Recomend 0.
    # maxrep: If algorithm does not converge in maxiter iterations, the pipeline will try again this number of times. This allows restarting of non-converged fits.
    # est_L: currently unused
    # gfa_seed: Seed for GFA. This can be a list, in which case multiple fits will be done using different seeds.
    # R: Specifies options for how correlation is estimated. Type can be either "ldsc" or "pt" for the p-threshold method. LDSC is likely better.
    # pthresh specifies the threshold for the p-threshold method. l2_dir gives the location of ld scores, required if using method "ldsc".
    gfa_params: "default"
    mode: "z-score"
    nmiss_thresh: 0
    maxrep: 5
    est_L: FALSE
    gfa_seed: [1]
    R:
        type: "ldsc"
        pthresh: "NA"
            l2_dir: "/nfs/turbo/sph-jvmorr/ld_reference_files/ldsc_reference_files/eur_w_ld_chr/"

out:
    # Output data options:
    # data_dir: Directory to store reformatted data
    # formatted_gwas_dir: Where do store formatted gwas data
    # output_dir: Where to store results
    data_dir: "data/"
    formatted_gwas_dir: "/nfs/turbo/sph-jvmorr/gwas_summary_statistics/formatted_data/gfa/"
    output_dir: "results/"

