# sum_stats is a csv file
input:
    sum_stats: "astle_bloodcell.csv"
    label: "bc"

analysis:
    # LD pruning options:
    # r2_thresh: threshold for pairwise r^2 between variants
    # clump_kb Maximum distance for pruning.
    # ref_path Path to plink format reference data
    # ld_prioritization: either pvalue or rank
    ldprune:
        r2_thresh: 0.01
        clump_kb: [1000]
        ld_prioritization: ["pvalue"] # "pvalue" or "rank"
        ref_path: "/nfs/turbo/sph-jvmorr/ld_reference_files/1kg_plink/EUR"
    # GFA options:
    # gfa_params: If "default", will use default parameters, otherwise provide a .RDS file containing a prameter list eg "list(max_iter = 500)".
    # mode: Either "z-score" to use z-score or "b-std" to use standardized effect estimates.
    # nmiss_thresh: Maximum number of missing studies per snp. Currently fixed at 0
    # max_snps: largest number of variants to allow
    # maxrep: If algorithm does not converge in maxiter iterations, the pipeline will try again this number of times. This allows restarting of non-converged fits.
    # gfa_seed: Seed for GFA. This can be a list, in which case multiple fits will be done using different seeds.
    # R: Specifies options for how correlation is estimated. Type can be either "ldsc", "pt", or "none".
    # LDSC or pt will both work. pt is faster and generally gives nearly identical results to LDSC.
    gfa_params: "default"
    cond_num: 1e3
    mode: "z-score"
    method: ["fixed_factors"]
    max_snps: Inf
    maxrep: 5
    gfa_seed: 1
    af_thresh: 0.01
    sample_size_tol: 0.1
    R:
        type: ["pt", "ldsc"] #,"ldsc" "ldsc_quick"]
        pthresh: [0.05]
        l2_dir: "/nfs/turbo/sph-jvmorr/ld_reference_files/ldsc_reference_files/eur_w_ld_chr/"
        cor_clust: [1, 0.98, 0.95]

out:
    # Output data options:
    # data_dir: Directory to store reformatted data
    # formatted_gwas_dir: Where do store formatted gwas data
    # output_dir: Where to store results
    data_dir: "data/"
    formatted_gwas_dir: "/nfs/turbo/sph-jvmorr/gwas_summary_statistics/formatted_data/gfa/"
    output_dir: "results/"

